Travis matrix
caroleolivier/caroleolivier.github.io pull request #22
Opened 2017-10-31 11:04 UTC by caroleolivier

2017-10-31 11:04 UTC, caroleolivier commented
I new new reviewers...

2017-10-31 11:36 UTC, caroleolivier commented on _posts/2017-10-31-building-multiple-project-with-travis.md
> +I am currently writing an application composed of a web application and a data api. I decided to put all the code in one repo (one could argue I should have put them in different repo but this is not
can one say repo?

2017-11-01 18:55 UTC, caroleolivier commented
testing, hi simon @simonproffitt

2017-11-01 19:00 UTC, simonproffitt requested changes
Ah! It was pending!!!

2017-11-01 19:00 UTC, simonproffitt commented on _posts/2017-10-31-building-multiple-project-with-travis.md
> +Note that [Travis linter](https://lint.travis-ci.org/) can't parse the code and returns a lot of errors. However, it works perfectly as you can see here:
Do you know why that is? Perhaps worth a comment?

2017-11-01 19:00 UTC, simonproffitt commented on _posts/2017-10-31-building-multiple-project-with-travis.md
> +I am currently writing an application composed of a web application and a data api. I decided to put all the code in one repo (one could argue I should have put them in different repo but this is not
Repo is fine but informal

2017-11-01 19:27 UTC, simonproffitt approved these changes

2017-11-01 19:31 UTC, merged