Typescript
caroleolivier/caroleolivier.github.io pull request #28
Opened 2017-11-28 12:35 UTC by caroleolivier

Let me know what you think. I wasn't sure what to make the article about. At the end it's a mix of what I think, my setup with TypeScript and a few gotchas.
I wonder if I should have reduced the scope.

2017-11-30 21:16 UTC, simonproffitt requested changes
A really nice article, I definitely understood it better because of your previous article which I think you should reference. A handful of grammatical changes to make

2017-11-30 21:16 UTC, simonproffitt commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +Yesterday I added support for [TypeScript](https://www.typescriptlang.org/) to my [minimal-react-starter](https://github.com/caroleolivier/minimal-react-starter/releases/tag/v6.0.0) project. I am sha
I _will_ ~am~ share~ing~

2017-11-30 21:16 UTC, simonproffitt commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +My background as a developer is C# and I looove this language. I really love statically-typed languages. I love their compile time safetiness and I love the intellisense that comes with them. So when
term_s_ of productivity

2017-11-30 21:16 UTC, simonproffitt commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +Hence, it is not surprising I am exploring alternatives to JavaScript for developing web applications, and TypeScript seems to be the most popular option at the moment. TypeScript is **optionally sta
superset is one word I think 

~thereof~ therefor 

I can migrate my Javascript code iteratively to Typescript ... reads more nicely

2017-11-30 21:16 UTC, simonproffitt commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +I won't go into more details here, but I recommend reading TypeScript Wikipedia [page](https://en.wikipedia.org/wiki/TypeScript), it has some very good information (for instance the history part is v
detail~s~

_the_ TypeScript Wikipedia

2017-11-30 21:16 UTC, simonproffitt commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +I would say the main "problem" is probably to decide what tool is responsible for what. For instance, should tsc, the TypeScript compiler, compile to ES5 or should it compile to ES6 and then Babel wo
~to decide~ deciding

2017-11-30 21:16 UTC, simonproffitt commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +I would say the main "problem" is probably to decide what tool is responsible for what. For instance, should tsc, the TypeScript compiler, compile to ES5 or should it compile to ES6 and then Babel wo
'Otherwise' reads better than 'else'

2017-11-30 21:16 UTC, simonproffitt commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +Next I looked at how to test a React Component written in TypeScript. I stuck to TypeScript to write the tests too (as opposed to use JavaScript) as, ultimately, I want all my code base to be written
~use~ using

2017-11-30 21:16 UTC, simonproffitt commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +You can take a look at my changes in my GitHub [repository](https://github.com/caroleolivier/minimal-react-starter/commit/f04477c0783e7216f661f53b20c9a40b1f259a00), else below is a summary of the cha
Again 'otherwise' reads better than 'else'

2017-11-30 21:16 UTC, simonproffitt commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +Please note this is not a tutorial about [TypeScript](https://www.typescriptlang.org/), [React](https://reactjs.org/), [Babel](https://babeljs.io), [webpack](webpack.js.org) or [Jest](https://faceboo
Maybe reference your previous Babel/Webpack article as that's what gave me the background needed to understand this one

2017-11-30 21:16 UTC, simonproffitt commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +The project I am working on uses [webpack](webpack.js.org) as a JavaScript bundler and [Babel](https://babeljs.io) as a JavaScript transpiler to transpile JavaScript ES6 to ES5. If I add TypeScript t
Missing an 'http://' before the webpack link?

2017-12-01 10:19 UTC, caroleolivier commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +Yesterday I added support for [TypeScript](https://www.typescriptlang.org/) to my [minimal-react-starter](https://github.com/caroleolivier/minimal-react-starter/releases/tag/v6.0.0) project. I am sha
Aaaaaaaaargh 😠

2017-12-01 10:24 UTC, caroleolivier commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +Hence, it is not surprising I am exploring alternatives to JavaScript for developing web applications, and TypeScript seems to be the most popular option at the moment. TypeScript is **optionally sta
oops
👍 
👍

2017-12-01 10:30 UTC, caroleolivier commented on _posts/2017-11-28-using-typescript-with-react-webpack-babel-jest.md
> +I won't go into more details here, but I recommend reading TypeScript Wikipedia [page](https://en.wikipedia.org/wiki/TypeScript), it has some very good information (for instance the history part is v
Did you get a chance to read the wikipedia page? The history section is genuinely interesting :)

2017-12-04 00:03 UTC, simonproffitt approved these changes
I think it's good to go! Nice article, Carole :)

2017-12-04 09:13 UTC, merged