Add new article about constructor function and function context
caroleolivier/caroleolivier.github.io pull request #32
Opened 2018-01-20 19:14 UTC by caroleolivier

2018-01-20 20:44 UTC, simonproffitt requested changes
This is really interesting, and something I didn't know anything about. From what you found out, do you think there are any coding best practices that might be adopted to make reading code that uses 'this' less confusing or do you think it's more about really understanding what's going on as you've outlined in this post?

2018-01-20 20:44 UTC, simonproffitt commented on _posts/2018-01-20-constructor-function-and-function-context-in-javascript.md
> +title: Constructor function and function context in JavaScript
I think this should probably be 'constructor function_s_ '

2018-01-20 20:44 UTC, simonproffitt commented on _posts/2018-01-20-constructor-function-and-function-context-in-javascript.md
> +First of all, what is a constructor function? A constructor function is a function that allows you to create an instance of an object when it is called. So every time you call it, you get a new objec
~that~ _this_

2018-01-20 21:50 UTC, caroleolivier commented
It is a good point. ES6 classes really help I think. I added a sentence at the end, lazy me! I could have gone into more details buuuuut I don't feel like it haha.

2018-01-21 09:15 UTC, simonproffitt requested changes
One thing I missed then it's good to go - perhaps es6 classes might be a future blog topic?

2018-01-21 09:15 UTC, simonproffitt commented on _posts/2018-01-20-constructor-functions-and-function-context-in-javascript.md
> +And you call it like with the `new` keyword:
Sorry, missed this the first time - don't need the 'like' here 'call it with the new keyword'

2018-01-22 08:02 UTC, simonproffitt approved these changes

2018-01-22 08:12 UTC, merged